version: "3.8"

services:
  mysqlserver:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: "testedb"
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ../mysqlserver/volumes:/var/lib/mysql
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge      