version: "3.8"

services:
  mysqlserver:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'P4ssw0rd'
    ports:
      - 3306:3306
    volumes:
      - ./volumes:/var/lib/mysql
    networks:
      - mysql-network

networks: 
  mysql-network:
    driver: bridge      