version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./volumes/data/:/var/lib/rabbitmq/
        - ./volumes/log/:/var/log/rabbitmq
    networks:
        - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge