version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "P4ssw0rd"
      MONGO_INITDB_USERNAME: "mdbuser"
      MONGO_INITDB_PASSWORD: "P4ssw0rd" # Senha do novo usuário não root
    ports:
      - 27017:27017
    volumes:
      - ./volumes:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
