version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      SA_PASSWORD: "P4ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
        - './volumes:/var/opt/mssql'
    networks:
        - "mssql-network"
    
networks: 
  mssql-network:
    driver: bridge